config:
  opensearch.yml: |
    cluster.name: opensearch-cluster
    network.host: 0.0.0.0

extraEnvs:
  - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
    value: Strong_password1

persistence:
  enabled: true
  size: 30Gi
  storageClass: nfs-storage

resources:
  requests:
    memory: "4Gi"
    cpu: "2"
  limits:
    memory: "8Gi"
    cpu: "4"

replicas: 3

image:
  repository: opensearchproject/opensearch
  tag: "3.3.0"
securityConfig:
  enabled: false

podSecurityContext:
  fsGroup: null

sysctlInit:
  enabled: false
